### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by danielf** [rk454/6125#1]
Good job so far! A few comments:

1) Avoid using range unless you really need it. In all the cases range is being used in your code you could have used xrange. Let me know if you don't know the difference, I would be happy to explain it to you.

2) That's the cleanest Strassen code I've ever seen! Congrats :)

3) Since Strassen is supposed to be O(n^(log_2(7)), I would like a plot that proves it. Plot the performance of both Strassen and the Standard Product in a log-log chart. We should see the slope of Strassen's being (slightly) smaller than that of the standard product. It may be slower, though, this is OK for now.

4) After you do the changes above, try using a numpy array for your matrices. Do not use any function of numpy (like the matrix multiplication one :P), only the array. It takes several times less to access an element of a numpy array than a regular list in python.

5) Python is notoriously slow when dealing with loops. Try your best to avoid them. List comprehensions are the way to go. As a quick example, instead of doing:
for i in range(halfsize):
            for j in range(halfsize):
                A11[i][j] = A[i][j]

Do:
A11 = [x[:halfsize] for x in A[:halfsize]]

Good job so far, good luck with the rest of the project

**Comment by njian** [comment]
All issues fixed. Updated 2 log-log performance plots for the multiplication of two random matrices. It can be seen that Strassen is still slower for matrix of size 2^10, but the line has a slightly smaller slope, so we would hope that it will intersect the line of standard product for matrix of larger size. Unfortunately the computational time would be beyond 12 hours for matrix bigger than 2^11.
